version: '3.8'

services:

  frontend:
    build: .
    ports:
      - "8080:80"

  backend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./src/assets:/app
    command: npx json-server db.json --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"